### ISSUE TITLE
Long text in bounty descriptions breaking scaling

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#108]
Currently longstrings of text within bounty descriptions breaks mobile scaling. See URL in description below:

![Screen Shot 2024-05-11 at 9 17 13 PM](https://github.com/picsoritdidnthappen/poidh-app/assets/152807131/2e22f9b3-abd3-4a03-91b9-15be855ebd7c)

Need to ensure long strings properly wrap to next line instead of breaking the screen

**Comment by defichopper** [comment]
Think this issue should be closed
