### ISSUE TITLE
ENS/Degen name display on profile pages breaks screen

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#113]
Mobile screen broken by length of profile name

<img width="625" alt="Screen Shot 2024-05-15 at 11 33 46 AM" src="https://github.com/picsoritdidnthappen/poidh-app/assets/152807131/14c6940f-c5c9-448a-a32b-7ce71fdebc2e">

Font size of name should dynamically adjust to ensure it stays within the screen

**Comment by gabrieltemtsen** [comment]
Please assign this to me

**Comment by picsoritdidnthappen** [comment]
@gabrieltemtsen assigned!

**Comment by gabrieltemtsen** [comment]
https://github.com/picsoritdidnthappen/poidh-app/pull/172
