### ISSUE TITLE
Copy + past icon for addresses in bounty cards

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#131]
Currently users cannot easily copy the address from a bounty card:

![Screen Shot 2024-05-27 at 9 33 48 AM](https://github.com/picsoritdidnthappen/poidh-app/assets/152807131/ae607fd6-c49f-4789-988c-e5c0cd7223e8)

Need to tweak these cards so that they have a copy + paste icon that is clickable and copies the full address to a user's clipboard. See example below (actual icon should use a white outline to match the rest of the site's design):

![Screen Shot 2024-05-27 at 9 36 56 AM](https://github.com/picsoritdidnthappen/poidh-app/assets/152807131/6aa2e55a-e74a-4815-adc5-48f4db3f7d79)

**Comment by ie2173** [comment]
Pull request #133 Submitted.
