### ISSUE TITLE
Refresh and redirect to bounty URL after bounty confirmation

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#163]
After a new bounty is successfully created, the user that created the bounty should be redirected to the URL for their new bounty. Please ensure that this works across all three chains https://poidh.xyz/arbitrum https://poidh.xyz/base and https://poidh.xyz/degen

**Comment by petersim1** [comment]
I’ll open a PR for this shortly!
