### ISSUE TITLE
Don't force lowercase on bounty descriptions

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#186]
Written bounty descriptions use the forced lowercase setting, but this can cause problems if the bounty creator needs to have uppercase letters in their description. See example below from this page https://poidh.xyz/degen/bounty/336

![Screen Shot 2024-06-17 at 7 50 35 AM](https://github.com/picsoritdidnthappen/poidh-app/assets/152807131/cba556b3-89b4-4964-bce4-ef61200a4742)

Update settings so that bounty description areas are not forced to be lowercase.

**Comment by gabrieltemtsen** [comment]
Please Assign this to me

**Comment by picsoritdidnthappen** [comment]
@gabrieltemtsen assigned!
