### ISSUE TITLE
Ability to hide the "create bounty" joystick button

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#195]
We want the "create bounty" button on the homepages to be hidden when people scroll the page down, but then to display again when people scroll up the page. This should happen on both desktop and mobile.

On individual bounty pages (like this one https://poidh.xyz/base/bounty/52) the same dynamic with hide/show based on scroll should be put in place for the "create claim" button on mobile. The create claim button is fixed on desktop, so it's not an issue there.

**Comment by gabrieltemtsen** [comment]
please assign this to me :)

**Comment by picsoritdidnthappen** [comment]
assigned!
