### ISSUE TITLE
Loading animation when bounties are being created

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#209]
After a user has submitted a new bounty, there is a long loading period where we are waiting for the transaction to be confirmed before the user is redirect to their new bounty URL. During this time, we should use some sort of loading animation (preferably a spinning wheel) that shows users work is being done, and that the bounty will be confirmed shortly.

**Comment by gabrieltemtsen** [comment]
Please assign this also

**Comment by picsoritdidnthappen** [comment]
@gabrieltemtsen assigned!
