### ISSUE TITLE
Update create claim submission button color

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#210]
The create claim button on the claim submission form blends in too much:

<img width="469" alt="Screen Shot 2024-06-27 at 9 52 56 AM" src="https://github.com/picsoritdidnthappen/poidh-app/assets/152807131/1bf6e2ab-6b2e-400b-939e-64a990645ce6">

Button color should be updated to the standard poidh red that we use elsewhere on the site (RGB 241 94 95).

**Comment by gabrieltemtsen** [comment]
please assign

**Comment by picsoritdidnthappen** [comment]
@gabrieltemtsen assigned!
