### ISSUE TITLE
Rainbow Browser wallet automatic popup

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#240]
Currently when users visit poidh with Rainbow Browser wallet active, they immediately get a popup to connect their wallet. This should only happen if they click the connect wallet button. This does not happen with MetaMask or other browser wallets, to my knowledge.

**Comment by laalauren1** [comment]
> Currently when users visit poidh with Rainbow Browser wallet active, they immediately get a popup to connect their wallet. This should only happen if they click the connect wallet button. This does not happen with MetaMask or other browser wallets, to my knowledge.

@picsoritdidnthappen It seems like there might be a specific issue with Rainbow Browser wallet triggering the popup.It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID RAI07638
Please see the link below to our dedicated support line:
[Rainbow Network DApps Support Ticket Requests](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by yukigesho** [comment]
It’s not reproducible after refactoring. I think you can close this issue.
