### ISSUE TITLE
Accept button fragment after accepting bounty

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#376]
After accepting a claim and the page refreshing you still see (for a short period of time) the "accept" button fragment under the new accepted button:

![Screen Shot 2024-11-14 at 8 55 12 PM](https://github.com/user-attachments/assets/4395d210-a819-49af-a78e-833b0a93891f)

The "accept" button also continues to display on claims that were not selected. Need to make sure that the "accept" button on all claims disappears as soon as "accepted" is displayed.

**Comment by yukigesho** [comment]
fixed
