### ISSUE TITLE
Update dropdown menu styling

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#437]
Need to update the styling of the dropdown menus for the sorting feature and the chain select feature:

![Screen Shot 2024-12-22 at 9 02 51 PM](https://github.com/user-attachments/assets/26deb594-fbce-4893-8ff5-e89e8532c437)
![Screen Shot 2024-12-22 at 9 03 19 PM](https://github.com/user-attachments/assets/bd81c823-5388-4346-8fd3-4cef41d9df36)

These menus should use the same light blue color as the menu buttons and their font style should be the same as the font used for the wallet address in the screenshot above.

**Comment by Hushg2** [comment]
Hello @picsoritdidnthappen  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
