### ISSUE TITLE
Mobile bounty issues address scaling

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#49]
On mobile, the bounty issuer address sometimes bleeds off the right hand of the screen

Need to scale it properly so that it either wraps around to a second line OR we shrink the font size based on screen size only for the address

![photo_4988095969157557459_y](https://github.com/picsoritdidnthappen/poidh-app/assets/152807131/32160c16-c981-4eb5-b67c-78bd384d7986)

**Comment by defichopper** [comment]
This issue should be closed
