### ISSUE TITLE
Add multiplayer icon to open bounty bounty cards

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#71]
Need a way for people to quickly see which bounties are "open" when browsing cards. Can add a multiplayer icon similar to this next to the DEGEN amount for each card. This example uses a black outline, but outline in prod should be white to match branding:

![Screen Shot 2024-04-29 at 11 17 43 AM](https://github.com/picsoritdidnthappen/poidh-app/assets/152807131/fc778f3c-f989-4e25-b4b7-81a695f8d69a)

**Comment by petersim1** [comment]
should this only be for the /account page, or for the main search page?

**Comment by picsoritdidnthappen** [comment]
@petersim1 so this should be on both /account/ pages and the main search page

When I was looking over the preview, I also noticed that the icon is only being applied to all bounty cards: 

![Screen Shot 2024-05-02 at 12 41 19 PM](https://github.com/picsoritdidnthappen/poidh-app/assets/152807131/ea6a46cb-89a0-460d-803d-d811208d5381)

To be clear, we only want this on "open" (otherwise known as "multiplayer") bounties. I'm still working on the blog that covers the slight different in these types of bounties, but you can get the general idea via what I've already written: https://paragraph.xyz/@poidh/preview/cMyjihgBzCCVDR1CUTRP

I understand this is confusing because we use the term "open bounties" on the main search page to also designate "any bounty that hasn't already been claimed", so I'll work on how we adjust that terminology to make things clearer moving forward. But for now worth noting that the purpose of this task is to allow people to quickly see what bounties have multiplayer/open capabilities, not just to add the icon to every bounty card.

**Comment by petersim1** [comment]
@picsoritdidnthappen Yup! Still a WIP, just needed clarification first on that terminology, but this is helpful. Working on changes
