### ISSUE TITLE
Add .degen names + .ens names on bounty pages

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#88]
Instructions here: https://gist.github.com/tempe-techie/2e14a9371aa40a286a8442e03ae7c8cf#reverse-resolver-defaultnames-get-users-degen-name

**Comment by tempe-techie** [comment]
Bounty was issued for this task: https://degen.poidh.xyz/bounty/205 

### Local enviromnent

Make sure to pull the `staging` branch: https://github.com/picsoritdidnthappen/poidh-app/tree/staging 

### Bounty instructions

- Show `.degen` or `.eth` name as the "bounty issuer" on a bounty page.
- If bounty issuer has a `.degen` name, show it.
- If issuer does not have a `.degen` name, show their `.eth` name.
- If issuer has neither of these, show the address (as it is right now).
- Do the same in the contributors section on the bounty page.

![](https://i.postimg.cc/3N8nmxC0/poidh-addresses.png)

### How to implement web3 names

**.degen names:**

```js
const degenNameContract = new ethers.Contract(
  "0x4087fb91A1fBdef05761C02714335D232a2Bf3a1", 
  new ethers.utils.Interface(["function defaultNames(address) public override view returns(string memory)"]),
  provider
);

const userName = degenNameContract.defaultNames("0xb29050965A5AC70ab487aa47546cdCBc97dAE45D"); // returns "tempe"

const fullDegenName = username + ".degen"; // tempe.degen
```

**.eth names:**

```js
const ensName = provider.lookupAddress("0xb29050965A5AC70ab487aa47546cdCBc97dAE45D"); // returns "tempetechie.eth"
```

**Comment by defichopper** [comment]
Happy to take on this bounty!

**Comment by tempe-techie** [comment]
@defichopper Awesome!

**Comment by defichopper** [comment]
@tempe-techie just put up a PR for it

**Comment by tempe-techie** [comment]
@defichopper That was fast! 🔥 Good job!

@picsoritdidnthappen can you check PR #91 and merge it? I've checked it and it looks alright to me.

**Comment by defichopper** [comment]
> @defichopper That was fast! 🔥 Good job!
> 
> @picsoritdidnthappen can you check PR #91 and merge it? I've checked it and it looks alright to me.

Nice good first issue for sure haha

**Comment by picsoritdidnthappen** [comment]
@tempe-techie @defichopper just checked, looks like the degen names work but the ENS names don't. This one should resolve to kaspotz.eth:

![Screen Shot 2024-05-07 at 7 08 42 AM](https://github.com/picsoritdidnthappen/poidh-app/assets/152807131/072fc731-d668-4d07-a87c-9a2c61ab3e5e)

**Comment by tempe-techie** [comment]
@picsoritdidnthappen This address `0x0e467A0288A439BA2678eb7d3B0B64b01e2bBBfC` doesn't seem to have any ENS name set as default name for resolving.

It does own the `kaspotz.eth` name, but that name is not set as default name for that address.

**Comment by defichopper** [comment]
> @picsoritdidnthappen This address `0x0e467A0288A439BA2678eb7d3B0B64b01e2bBBfC` doesn't seem to have any ENS name set as default name for resolving.
> 
> It does own the `kaspotz.eth` name, but that name is not set as default name for that address.

The comment of `lookupAddress` says

> Users must perform additional steps to configure a //primary name//, which is not currently common.

So if we want to display an ENS name that is not the primary / default name of an address, then it looks like we need to do something like this here

https://docs.alchemy.com/docs/how-to-resolve-ens-domains-given-a-wallet-address

**Comment by tempe-techie** [comment]
@defichopper Yes, the name needs to be set as Primary. I think there's nothing wrong with your code. Kenny will set that kaspotz.eth name as Primary later today and try again 🙂 

Sorry for the false alarm 😅

**Comment by tempe-techie** [comment]
@defichopper Actually, I just commented out the part of the code that fetches .degen names to see if .eth name would appear on my bounty - and it did!

So the code works flawlessly 💯

**Comment by defichopper** [comment]
> @defichopper Actually, I just commented out the part of the code that fetches .degen names to see if .eth name would appear on my bounty - and it did!
> 
> So the code works flawlessly 💯

Awesome!
