### ISSUE TITLE
"past bounties" should not show cancelled bounties

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#92]
Currently the "past bounties" section on the homepage shows both completed bounties and cancelled bounties. We should filter this so only completed bounties are shown (people can still see their cancelled bounties via their profile pages if they'd like).

**Comment by gabrieltemtsen** [comment]
Please assign this to me

**Comment by gabrieltemtsen** [comment]
https://github.com/picsoritdidnthappen/poidh-app/pull/184
