### ISSUE TITLE
Add "voting in progress" view on homepage

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#93]
A separate view should be added to the homepage that allows users to see bounties with a vote in progress:

![Screen Shot 2024-05-07 at 9 51 49 AM](https://github.com/picsoritdidnthappen/poidh-app/assets/152807131/5289b6ef-fa79-4d47-bb4f-71c5a66f77e3)

Bounties with a vote in progress should also no longer be viewable via the "open bounties" section.

**Comment by petersim1** [comment]
Working on this.
