### ISSUE TITLE
Bounty cards don't show .degen or .ens name

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#94]
Now that we have names displayed for bounty creators and contributors, we need to also display names if they are available for bounty claim card issuers:

![Screen Shot 2024-05-07 at 10 17 55 AM](https://github.com/picsoritdidnthappen/poidh-app/assets/152807131/501cff3c-08f4-4daa-b578-1bb64ba094f5)

This needs to be done on both bounty detail pages (like this one: https://degen.poidh.xyz/bounty/209) AND under the "NFTs" and "Submitted Claims" section of profile pages like this one: https://degen.poidh.xyz/account/0xBeD82560c39c133A3d64516ecdA82C71b72f3Cd7

**Comment by defichopper** [comment]
Put up a PR for this

https://github.com/picsoritdidnthappen/poidh-app/pull/102
