### ISSUE TITLE
Add text explaining "solo" vs "open" bounty

### ISSUE THREAD

**Issue by picsoritdidnthappen** [picsoritdidnthappen/poidh-app#95]
Text should be added below the toggle that changes based on whether someone selects "solo" bounty or "open" bounty:

<img width="465" alt="Screen Shot 2024-05-07 at 2 03 24 PM" src="https://github.com/picsoritdidnthappen/poidh-app/assets/152807131/46d16edc-6411-4dee-b1fc-89ade8ddf7b0">

For solo, it should read "you are the sole bounty contributor"

For open, it should read "users can add additional funds to your bounty"

**Comment by gabrieltemtsen** [comment]
Please assign this issue to me

**Comment by picsoritdidnthappen** [comment]
@gabrieltemtsen done!

**Comment by gabrieltemtsen** [comment]
https://github.com/picsoritdidnthappen/poidh-app/pull/191
